### ISSUE TITLE
main.py 报错 KeyError: 'database'

### ISSUE THREAD

**Issue by xsw1006931693** [cubenlp/ChatSQL#21]
(chatsql) F:\chat\ChatSQL-main>python F:\chat\ChatSQL-main\main.py
Loading checkpoint shards:  14%|████████▏                                                | 1/7 [00:01<00:11,  1Loading checkpoint shards:  29%|████████████████▎                                        | 2/7 [00:03<0Loading checkpoint shards:  43%|████████████████████████▍                                | 3/7 Loading checkpoint shards:  57%|████████████████████████████████▌                      Loading checkpoint shards:  71%|████████████████████████████████████████▋      Loading checkpoint shards:  86%|████████████████████████████████████████████Loading checkpoint shards: 100%|████████████████████████████████████████████Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:12<00:00,  1.75s/it]
Traceback (most recent call last):
  File "F:\chat\ChatSQL-main\main.py", line 99, in <module>
    main()
  File "F:\chat\ChatSQL-main\main.py", line 31, in main
    db_con = Cur_db()
  File "F:\chat\ChatSQL-main\utility\db_tools.py", line 14, in __init__
    self.db_name = self.config['database']['DB']
  File "D:\work\miniconda3\envs\chatsql\lib\configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'database'

(chatsql) F:\chat\ChatSQL-main>a

**Comment by Mosquito0352** [comment]
你好  请问怎么解决的呢
